=== ZentoDev/gym-weight/src/main/resources/plates.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="weights">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="barbell">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="weightBarbell" type="xs:string" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="plates">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="plate" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="weight" type="xs:string" />
										<xs:element name="material" minOccurs="0" type="xs:string" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ZentoDev/gym-weight/src/main/resources/plates.xml
<weights xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="plates.xsd">
	<barbell>
		<weightBarbell>10</weightBarbell>
	</barbell>
	<plates>
		<plate>
			<weight>10.0</weight>
			<material>bumper</material>
		</plate>
		<plate>
			<weight>10.0</weight>
			<material>bumper</material>
		</plate>
		<plate>
			<weight>5</weight>
			<material>cast iron</material>
		</plate>
		<plate>
			<weight>5</weight>
			<material>cast iron</material>
		</plate>
		<plate>
			<weight>5</weight>
			<material>cast iron</material>
		</plate>
		<plate>
			<weight>5</weight>
			<material>cast iron</material>
		</plate>
		<plate>
			<weight>5</weight>
			<material>cast iron</material>
		</plate>
		<plate>
			<weight>5</weight>
			<material>cast iron</material>
		</plate>
		<plate>
			<weight>5</weight>
			<material>cast iron</material>
		</plate>
		<plate>
			<weight>5</weight>
			<material>cast iron</material>
		</plate>
		<plate>
			<weight>5</weight>
			<material>bumper</material>
		</plate>
		<plate>
			<weight>5</weight>
			<material>bumper</material>
		</plate>
		<plate>
			<weight>2.5</weight>
			<material></material>
		</plate>
		<plate>
			<weight>2.5</weight>
		</plate>
		<plate>
			<weight>2.5</weight>
			<material>cast iron</material>
		</plate>
		<plate>
			<weight>2.5</weight>
			<material>cast iron</material>
		</plate>
		<plate>
			<weight>1</weight>
			<material>cast iron</material>
		</plate>
		<plate>
			<weight>1</weight>
			<material>cast iron</material>
		</plate>
		<plate>
			<weight>0.5</weight>
			<material>cast iron</material>
		</plate>
		<plate>
			<weight>0.5</weight>
			<material>cast iron</material>
		</plate>
	</plates>
</weights>
